# Generated by Django 5.0.6 on 2024-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='access_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
